services:
  lima:
    image: ghcr.io/r-dvl/lima/lima:latest
    pull_policy: always
    container_name: lima
    volumes:
      - data:/app/data
    ports:
      - 32500:8000
    restart: unless-stopped

volumes:
  data: