version: '3.8'
services:

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend/lima-frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:3001
    ports:
      - '3000:3000'

  api:
    container_name: backend
    restart: always
    build:
      context: ./backend/lima-backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://localhost:27017
    ports:
      - '3001:3001'

  database:
    container_name: database
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  cat-watcher:
    container_name: cat-watcher
    restart: unless-stopped
    build:
      context: ./apps/cat-watcher
      dockerfile: Dockerfile
    environment:
      - API_URL=http://localhost:3001
      - TOKEN=