services:
  lima:
    image: ghcr.io/r-dvl/lima/lima:latest
    container_name: ams-invoice-control
    volumes:
      - data:/app/data
    ports:
      - 8000:8000
    restart: unless-stopped

volumes:
  data: