# Generated by Django 4.2.16 on 2024-11-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantity_at_home',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantity_to_buy',
        ),
        migrations.AddField(
            model_name='article',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
