# Generated by Django 4.2.16 on 2024-11-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantity_to_buy',
            field=models.IntegerField(default=0),
        ),
    ]
