name: Deploy

on:
    workflow_dispatch:
        inputs:
            domain:
              description: 'Portainer domain'
              required: true
              type: string
            image:
              description: 'Docker image to deploy'
              required: true
              type: string
            stack_id:
              description: 'Portainer Stack ID'
              required: true
              type: string

jobs:
    deploy:
        uses: r-dvl/reusable-workflows/.github/workflows/deploy-portainer.yml@main
        with:
            domain: ${{ inputs.domain }}
            image: ${{ inputs.image }}
            stack_id: ${{ inputs.stack_id }}
